//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mawenzy.Plugins.GooglePlugins {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class GoogleSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GoogleSettings defaultInstance = ((GoogleSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GoogleSettings())));
        
        public static GoogleSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CompressTextures {
            get {
                return ((bool)(this["CompressTextures"]));
            }
            set {
                this["CompressTextures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600000")]
        public int SwapInterval {
            get {
                return ((int)(this["SwapInterval"]));
            }
            set {
                this["SwapInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public char TempUnits {
            get {
                return ((char)(this["TempUnits"]));
            }
            set {
                this["TempUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://news.google.com/?geo={REGION}")]
        public string NewsURL {
            get {
                return ((string)(this["NewsURL"]));
            }
            set {
                this["NewsURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRefreshNews {
            get {
                return ((bool)(this["AutoRefreshNews"]));
            }
            set {
                this["AutoRefreshNews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleID {
            get {
                return ((string)(this["GoogleID"]));
            }
            set {
                this["GoogleID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GooglePW {
            get {
                return ((string)(this["GooglePW"]));
            }
            set {
                this["GooglePW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CalendarStyle {
            get {
                return ((string)(this["CalendarStyle"]));
            }
            set {
                this["CalendarStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public decimal GoogleMarqueeSpeed {
            get {
                return ((decimal)(this["GoogleMarqueeSpeed"]));
            }
            set {
                this["GoogleMarqueeSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.google.com/calendar/feeds/default/private/full")]
        public string CalendarURL {
            get {
                return ((string)(this["CalendarURL"]));
            }
            set {
                this["CalendarURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.wunderground.com/cgi-bin/findweather/getForecast?query={REGION}&wuSele" +
            "ct=WEATHER")]
        public string WeatherURL {
            get {
                return ((string)(this["WeatherURL"]));
            }
            set {
                this["WeatherURL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://img0.gmodules.com/")]
        public string WeatherImagePath {
            get {
                return ((string)(this["WeatherImagePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.google.com/ig/api?weather={0}")]
        public string GoogleWeatherURL {
            get {
                return ((string)(this["GoogleWeatherURL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5,0,0,-1400,0")]
        public string CalendarCamPos {
            get {
                return ((string)(this["CalendarCamPos"]));
            }
            set {
                this["CalendarCamPos"] = value;
            }
        }
    }
}
