//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mawenzy.Plugins {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class PluginSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PluginSettings defaultInstance = ((PluginSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PluginSettings())));
        
        public static PluginSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>*.jpg</string>
  <string>*.jpeg</string>
  <string>*.png</string>
  <string>*.bmp</string>
  <string>*.gif</string>
  <string>*.tif</string>
  <string>*.tiff</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SuppImageTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SuppImageTypes"]));
            }
            set {
                this["SuppImageTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNewPlugins {
            get {
                return ((bool)(this["ShowNewPlugins"]));
            }
            set {
                this["ShowNewPlugins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public decimal FPS {
            get {
                return ((decimal)(this["FPS"]));
            }
            set {
                this["FPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Middle")]
        public global::System.Windows.Forms.MouseButtons StickerMouseButton {
            get {
                return ((global::System.Windows.Forms.MouseButtons)(this["StickerMouseButton"]));
            }
            set {
                this["StickerMouseButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://quote.yahoo.com/d/quotes.csv?s={0}&f={1}")]
        public string StockURL {
            get {
                return ((string)(this["StockURL"]));
            }
            set {
                this["StockURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MawenzyMarqueeSpeed {
            get {
                return ((int)(this["MawenzyMarqueeSpeed"]));
            }
            set {
                this["MawenzyMarqueeSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GradientActiveCaption")]
        public global::System.Drawing.Color StickerBackColor {
            get {
                return ((global::System.Drawing.Color)(this["StickerBackColor"]));
            }
            set {
                this["StickerBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ActiveCaption")]
        public global::System.Drawing.Color StickerBottomColor {
            get {
                return ((global::System.Drawing.Color)(this["StickerBottomColor"]));
            }
            set {
                this["StickerBottomColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^DJI,^IXIC,^GSPC")]
        public string StickerSymbols {
            get {
                return ((string)(this["StickerSymbols"]));
            }
            set {
                this["StickerSymbols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public decimal SnailMaxPics {
            get {
                return ((decimal)(this["SnailMaxPics"]));
            }
            set {
                this["SnailMaxPics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Snail3DMode {
            get {
                return ((string)(this["Snail3DMode"]));
            }
            set {
                this["Snail3DMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SnailBlurQuality {
            get {
                return ((int)(this["SnailBlurQuality"]));
            }
            set {
                this["SnailBlurQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SnailRotateOnMouseWheel {
            get {
                return ((bool)(this["SnailRotateOnMouseWheel"]));
            }
            set {
                this["SnailRotateOnMouseWheel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SlideShowPath {
            get {
                return ((string)(this["SlideShowPath"]));
            }
            set {
                this["SlideShowPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int SlideShowDuration {
            get {
                return ((int)(this["SlideShowDuration"]));
            }
            set {
                this["SlideShowDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SlideShowSpeed {
            get {
                return ((int)(this["SlideShowSpeed"]));
            }
            set {
                this["SlideShowSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SlideShowCompress {
            get {
                return ((bool)(this["SlideShowCompress"]));
            }
            set {
                this["SlideShowCompress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection RSSAddressList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RSSAddressList"]));
            }
            set {
                this["RSSAddressList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53092")]
        public string NewsRegion {
            get {
                return ((string)(this["NewsRegion"]));
            }
            set {
                this["NewsRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://news.google.com/?geo={REGION}")]
        public string NewsURL {
            get {
                return ((string)(this["NewsURL"]));
            }
            set {
                this["NewsURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int NewsSwapInterval {
            get {
                return ((int)(this["NewsSwapInterval"]));
            }
            set {
                this["NewsSwapInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewsAutoRefresh {
            get {
                return ((bool)(this["NewsAutoRefresh"]));
            }
            set {
                this["NewsAutoRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys StickerModifierKeys {
            get {
                return ((global::System.Windows.Forms.Keys)(this["StickerModifierKeys"]));
            }
            set {
                this["StickerModifierKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://finance.yahoo.com/q?s={0}")]
        public string StickerLinkFormat {
            get {
                return ((string)(this["StickerLinkFormat"]));
            }
            set {
                this["StickerLinkFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal RSS_MaxItems {
            get {
                return ((decimal)(this["RSS_MaxItems"]));
            }
            set {
                this["RSS_MaxItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Random")]
        public string SlideShow_rotationMode {
            get {
                return ((string)(this["SlideShow_rotationMode"]));
            }
            set {
                this["SlideShow_rotationMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RSS_RotationMode {
            get {
                return ((string)(this["RSS_RotationMode"]));
            }
            set {
                this["RSS_RotationMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 1")]
        public global::System.Drawing.Color OverlayColor {
            get {
                return ((global::System.Drawing.Color)(this["OverlayColor"]));
            }
            set {
                this["OverlayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int QuasarDetail {
            get {
                return ((int)(this["QuasarDetail"]));
            }
            set {
                this["QuasarDetail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuasarPointSmooth {
            get {
                return ((bool)(this["QuasarPointSmooth"]));
            }
            set {
                this["QuasarPointSmooth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int QuasarCount {
            get {
                return ((int)(this["QuasarCount"]));
            }
            set {
                this["QuasarCount"] = value;
            }
        }
    }
}
