//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mawenzy.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mawenzy.Plugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap alerts {
            get {
                object obj = ResourceManager.GetObject("alerts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap apps_internet {
            get {
                object obj = ResourceManager.GetObject("apps_internet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap auto_16 {
            get {
                object obj = ResourceManager.GetObject("auto_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap banner {
            get {
                object obj = ResourceManager.GetObject("banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brd_b {
            get {
                object obj = ResourceManager.GetObject("brd_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brd_l {
            get {
                object obj = ResourceManager.GetObject("brd_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brd_r {
            get {
                object obj = ResourceManager.GetObject("brd_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brd_t {
            get {
                object obj = ResourceManager.GetObject("brd_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Calendar has a beef with you. It says &quot;{0}&quot;.
        /// </summary>
        internal static string CalendarCredErr {
            get {
                return ResourceManager.GetString("CalendarCredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Calendar has encountered an unrecoverable error and has disabled itself: {0}.
        /// </summary>
        internal static string CalendarFatalErr {
            get {
                return ResourceManager.GetString("CalendarFatalErr", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap calvin_32 {
            get {
                object obj = ResourceManager.GetObject("calvin_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calvin_faces {
            get {
                object obj = ResourceManager.GetObject("calvin_faces", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cc_history_48 {
            get {
                object obj = ResourceManager.GetObject("cc_history_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cc_yahoo_finance {
            get {
                object obj = ResourceManager.GetObject("cc_yahoo_finance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cert_compar_extensions {
            get {
                object obj = ResourceManager.GetObject("cert_compar_extensions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock_hand {
            get {
                object obj = ResourceManager.GetObject("clock_hand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_action_player_play {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_action_player_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_action_window_nofullscreen {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_action_window_nofullscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_app_desktopshare {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_app_desktopshare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_app_help_index {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_app_help_index", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_app_katomic {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_app_katomic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_app_logout {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_app_logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_app_mouse {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_app_mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_app_tutorials {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_app_tutorials", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_app_Volume_Manager {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_app_Volume_Manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_app_xclock {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_app_xclock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_mimetype_log {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_mimetype_log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap default_clock {
            get {
                object obj = ResourceManager.GetObject("default_clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_add {
            get {
                object obj = ResourceManager.GetObject("edit_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Weather connectivity failure..
        /// </summary>
        internal static string ERR_GWeather {
            get {
                return ResourceManager.GetString("ERR_GWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read desktop background picture..
        /// </summary>
        internal static string ERR_WinDesktop {
            get {
                return ResourceManager.GetString("ERR_WinDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo stock api is unaccessible..
        /// </summary>
        internal static string ERR_Yahoo_API {
            get {
                return ResourceManager.GetString("ERR_Yahoo_API", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap feed_16 {
            get {
                object obj = ResourceManager.GetObject("feed_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap highlight {
            get {
                object obj = ResourceManager.GetObject("highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_snail {
            get {
                object obj = ResourceManager.GetObject("icon_snail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open link: {0}.
        /// </summary>
        internal static string INFO_SymbolOpen {
            get {
                return ResourceManager.GetString("INFO_SymbolOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol: {0}.
        /// </summary>
        internal static string INFO_SymbolPrefix {
            get {
                return ResourceManager.GetString("INFO_SymbolPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh delay
        ///({0} sec):.
        /// </summary>
        internal static string LabRefresh {
            get {
                return ResourceManager.GetString("LabRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Marquee Speed ({0}/{1}):.
        /// </summary>
        internal static string MarqueeSpeed {
            get {
                return ResourceManager.GetString("MarqueeSpeed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap max_16 {
            get {
                object obj = ResourceManager.GetObject("max_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap min_16 {
            get {
                object obj = ResourceManager.GetObject("min_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mw {
            get {
                object obj = ResourceManager.GetObject("mw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mw_blur {
            get {
                object obj = ResourceManager.GetObject("mw_blur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap news {
            get {
                object obj = ResourceManager.GetObject("news", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap news_16 {
            get {
                object obj = ResourceManager.GetObject("news_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap news1 {
            get {
                object obj = ResourceManager.GetObject("news1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap no_16 {
            get {
                object obj = ResourceManager.GetObject("no_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap overlay {
            get {
                object obj = ResourceManager.GetObject("overlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap protoborderless {
            get {
                object obj = ResourceManager.GetObject("protoborderless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap protoframe {
            get {
                object obj = ResourceManager.GetObject("protoframe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quasar {
            get {
                object obj = ResourceManager.GetObject("quasar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quick_restart {
            get {
                object obj = ResourceManager.GetObject("Quick_restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh_16 {
            get {
                object obj = ResourceManager.GetObject("Refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rss {
            get {
                object obj = ResourceManager.GetObject("rss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rss_32 {
            get {
                object obj = ResourceManager.GetObject("rss_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rss_body {
            get {
                object obj = ResourceManager.GetObject("rss_body", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rss_brd_l {
            get {
                object obj = ResourceManager.GetObject("rss_brd_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rss_brd_t {
            get {
                object obj = ResourceManager.GetObject("rss_brd_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RSS feed &quot;{FEED}&quot; had connection problems and did not load..
        /// </summary>
        internal static string RSS_ConnectivityFail {
            get {
                return ResourceManager.GetString("RSS_ConnectivityFail", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rss_crn_tl {
            get {
                object obj = ResourceManager.GetObject("rss_crn_tl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There appears to be no &apos;channel&apos; tag in the feed {0}..
        /// </summary>
        internal static string RSS_Invalid_NoChannel {
            get {
                return ResourceManager.GetString("RSS_Invalid_NoChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There appears to be no RSS tag in the feed {0}..
        /// </summary>
        internal static string RSS_Invalid_NoRSSTag {
            get {
                return ResourceManager.GetString("RSS_Invalid_NoRSSTag", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap stickerHighlight {
            get {
                object obj = ResourceManager.GetObject("stickerHighlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap uberdash_32 {
            get {
                object obj = ResourceManager.GetObject("uberdash_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.mawenzy.com/uberdash.
        /// </summary>
        internal static string URLUberdash {
            get {
                return ResourceManager.GetString("URLUberdash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.uberdash.com/plugins/rssPolicy.html.
        /// </summary>
        internal static string URLUberdashRSSPolicy {
            get {
                return ResourceManager.GetString("URLUberdashRSSPolicy", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap weather {
            get {
                object obj = ResourceManager.GetObject("weather", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
