//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mawenzy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mawenzy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_action_configure {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_action_configure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_action_exit {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_action_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_action_lock {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_action_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_app_ark2 {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_app_ark2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_app_mouse {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_app_mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_not_found {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_not_found", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dn {
            get {
                object obj = ResourceManager.GetObject("dn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has caused Uberdash to quit.  Please try again or report this as an issue..
        /// </summary>
        internal static string ERR_GeneralUnhandled {
            get {
                return ResourceManager.GetString("ERR_GeneralUnhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error prevented your click from being handled:.
        /// </summary>
        internal static string ERR_MouseClick {
            get {
                return ResourceManager.GetString("ERR_MouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid modifier key was configured for mouse input.  Defaulting to &quot;None.&quot;.
        /// </summary>
        internal static string ERR_MouseKeys {
            get {
                return ResourceManager.GetString("ERR_MouseKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error prevented your mouse wheel from being handled:.
        /// </summary>
        internal static string ERR_MouseWheel {
            get {
                return ResourceManager.GetString("ERR_MouseWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humblest apologies as the options dialog had a problem..
        /// </summary>
        internal static string ERR_OptionsDialog {
            get {
                return ResourceManager.GetString("ERR_OptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uberdash plugin {0} has something to say: {1}.
        /// </summary>
        internal static string ERR_PluginException {
            get {
                return ResourceManager.GetString("ERR_PluginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch URL: {URL}.
        /// </summary>
        internal static string ERR_UrlFailure {
            get {
                return ResourceManager.GetString("ERR_UrlFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! Uberdash attempted to launch a web page that has been replaced with the file: &quot;{FILE}&quot;.  This is likely an attempted attack on your computer and the file will be skipped..
        /// </summary>
        internal static string ERR_UrlMalicious {
            get {
                return ResourceManager.GetString("ERR_UrlMalicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply settings.  See inner details..
        /// </summary>
        internal static string ErrSaving {
            get {
                return ResourceManager.GetString("ErrSaving", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap extensions {
            get {
                object obj = ResourceManager.GetObject("extensions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mw_blur {
            get {
                object obj = ResourceManager.GetObject("mw_blur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Install plugins at your own risk.  Plugins may execute arbitrarily and it is advised that only plugins that are approved by the Uberdash community be installed. If you download a plugin from a foreign source, install it at your own risk..
        /// </summary>
        internal static string PluginWarning {
            get {
                return ResourceManager.GetString("PluginWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///&lt;title&gt;Uberdash RSS link: {PAGE}&lt;/title&gt;
        ///
        ///&lt;style&gt;
        ///html{height:100%}
        ///body{margin:0;font:62.5% arial,sans-serif;height:100%;overflow:hidden}
        ///a,a:visited{color:#00c}
        ///div{font-size:130%}
        ///#details{float:left;margin-top:10px}
        ///#details p{padding:0;margin:0 0 2px}
        ///img{border:none}
        ///#outer-separator{clear:both;width:100%;border-bottom:2px solid #404040;border-top:1px solid #a0a0a0;margin:10px 0 0;padding:0;font-size:1px;ove [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SPN_AdLink {
            get {
                return ResourceManager.GetString("SPN_AdLink", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
